# Copy this file to settings.yml and update values to suit your migration.

# Rackspace username and API key.
rackspace:
  username:
  key:

# AWS IAM key id and secret. Ensure this IAM user has sufficient access to
# Route 53.
aws:
  id:
  secret:

# List of domains to migrate from Rackspace to Route 53.
domains:
  - example.com
  - example.net
  - example.org
